"""add local market data model

Revision ID: 625b7f31eddd
Revises: 9af5f061b335
Create Date: 2023-12-28 11:50:21.880190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625b7f31eddd'
down_revision: Union[str, None] = '9af5f061b335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('csi', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_traded_time', sa.DateTime(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('Bid', sa.Float(), nullable=True),
    sa.Column('ask_size', sa.Float(), nullable=True),
    sa.Column('Bid_size', sa.Float(), nullable=True),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.Column('prev_close_time', sa.DateTime(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('per_change', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('p_e', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('yearly_high', sa.Float(), nullable=True),
    sa.Column('yearly_low', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('traded_date', sa.DateTime(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_market_data')
    # ### end Alembic commands ###
