"""Initial migration

Revision ID: 9af5f061b335
Revises: f4300328de05
Create Date: 2023-11-09 14:16:53.672239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af5f061b335'
down_revision: Union[str, None] = 'f4300328de05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('purchase_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'purchase_price')
    # ### end Alembic commands ###
